# # route:
# #   receiver: 'mail'
# #   repeat_interval: 4s
# #   group_by: [ alertname ]


# # receivers:
# #   - name: 'mail'
# #     email_configs:
# #       - smarthost: 'smtp.gmail.com:465'
# #         auth_username: 'anasmfenjou@gmail.com'
# #         auth_password: "@n@s12345#"
# #         from: 'anasmfenjou@gmail.com'
# #         to: 'patriceneussi9gmail.com'


# global:
#   smtp_from: 'anasmfenjou@gmail.com'
#   smtp_smarthost: 'smtp.gmail.com:465'
#   smtp_auth_username: 'mfenjou'
#   smtp_auth_password: 'anascheriif'

# templates:
# - '/etc/alertmanager/template/*.tmpl'

# route:
#   group_by: ['alertname']
#   group_wait: 3s
#   group_interval: 5s
#   repeat_interval: 1h
#   receiver: mail-slack-receiver

# receivers:
# - name: 'mail-slack-receiver'
#   slack_configs:
#   - api_url: ''
#     channel: '#alerts'
#     send_resolved: true
#     icon_url: 'https://avatars3.githubusercontent.com/u/3380462'
#     text: >-
#          {{ range .Alerts - }}

#          *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
#          *Description:* {{ .Annotations.description }}
#          *Details:*
#            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
#           {{ end }}
#          {{ end }}
#   email_configs:
#    - to: 'anasmfenjou@gmail.com'
#      send_resolved: true
